[build]
  command = "npm ci && npm run build"
  publish = "dist"

# Optional: set environment via Netlify UI instead of committing secrets.
# [build.environment]
#   VITE_API_URL = "https://thesteezestoreserver1.onrender.com/api"

# Ensure SPA routes fallback to index.html
[[redirects]]
  from = "/api/*"
  to = "https://thesteezestoreserver1.onrender.com/api/:splat"
  status = 200
  force = true
  headers = { X-Forwarded-By = "Netlify" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
